sudo: required
services:
  - docker

before_install:
  - docker build -t dsamaddar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dsamaddar/docker-react npm test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-879655065789"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"